layout_spectrum: 0.044774982845410705
typography_spectrum: 0.2927993992343545
color:
  brandStrength: 0.9374864276032895
  lightness: 0.9304245077073574
  saturation: 0.7291049002669752
  rhythmicContrast: 0.8470994969829917
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
name: kennedylbailey.com
navigation:
  - name: Art Portfolio Website
    url: kennedybailey.com
    type: external
  - name: Instagram
    url: '@kennedyb.art'
    type: external
  - name: Facebook Page
    url: '@kennedybailey.art'
    type: external
  - name: The Hierarchy Series
    id: 6abc15f9-372a-4594-b743-6e5bfc6fc4ff
    type: content
